version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-blog
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
